import {
  GraduationCap,
  Target,
  FileText,
  CalendarCheck,
  Sparkles,
  Smartphone,
  Mail,
  Phone,
  MapPin,
  BookOpen,
  Trophy,
  Handshake,
  Lightbulb,
  Globe,
  BookMarked,
  Plane,
  Building2,
  FileEdit,
  User,
  Star,
  PenTool,
  Users,
  Puzzle,
  Award,
  Bot,
  BarChart3,
  type LucideIcon,
} from 'lucide-react';

const map: Record<string, LucideIcon> = {
  tutoring: GraduationCap,
  strategy: Target,
  documents: FileText,
  tracking: CalendarCheck,
  ai: Sparkles,
  mobile: Smartphone,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  book: BookOpen,
  trophy: Trophy,
  handshake: Handshake,
  lightbulb: Lightbulb,
  graduation: GraduationCap,
  globe: Globe,
  bookmarked: BookMarked,
  plane: Plane,
  building: Building2,
  fileEdit: FileEdit,
  user: User,
  star: Star,
  penTool: PenTool,
  users: Users,
  puzzle: Puzzle,
  award: Award,
  bot: Bot,
  barChart: BarChart3,
  target: Target,
};

export default function Icon({ name, size = 22 }: { name: string; size?: number }) {
  const Cmp = map[name] ?? Sparkles;
  return <Cmp size={size} strokeWidth={2} />;
}
